[build]
  command = "npm ci --legacy-peer-deps && npm run build"
  # ⬇️ pon aquí la carpeta que viste en dist/
  publish = "dist/TU_CARPETA/browser"  # o "dist/TU_CARPETA" si no existe /browser

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# SPA Angular: redirecciones al index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
